FROM ubuntu
WORKDIR /Project/xmrig
COPY . .
CMD ["/bin/bash"]

# 注：
# 创建镜像
# sudo docker build -t 'xmrig' . 
# 发布镜像
# 起 docker (临时)
# sudo docker run -it --rm --network container:miningovern xmrig
# 然后在里面运行 README 中的命令